## **Encoding Techniques**

**Key Takeaways:**

Label Encoding: Converts categories into numbers but may imply an order.

Ordinal Encoding: Converts categories into numbers while preserving their order (useful for ordinal data like size).

One-Hot Encoding: Creates new binary columns for each category, removing any implied order, making it suitable for nominal data.

In [ ]:
import pandas as pd
data={"Color":["Red","Blue" , "Red","Black"]   , "Size":["Large","Small","Medium" ,"Large" ],
      "Maritial staus" :["Single","Married" , "Relationship" , "Single"]}
df=pd.DataFrame(data)
df

   Color    Size Maritial staus
0    Red   Large         Single
1   Blue   Small        Married
2    Red  Medium   Relationship
3  Black   Large         Single

In [ ]:
# Label Encoding in Color column - Follow ALPHABETICAL ORDER

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
df["Color"]=le.fit_transform(df["Color"])
df

   Color    Size Maritial staus
0      2   Large         Single
1      1   Small        Married
2      2  Medium   Relationship
3      0   Large         Single

In [ ]:
# Ordinal Encoding in Size column
'''
Small = 0
Medium = 1
Large = 2
'''
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["Small" , "Medium" ,"Large"]])  # Manully define the order [0,1,2]
df["Size"]=oe.fit_transform(df[["Size"]])
df

   Color  Size Maritial staus
0      2   2.0         Single
1      1   0.0        Married
2      2   1.0   Relationship
3      0   2.0         Single

In [ ]:
# 1 hot Encoding in Maritial status column
df=pd.get_dummies(df ,columns=["Maritial staus"])
df

,Color,Size,Maritial staus_Married,Maritial staus_Relationship,Maritial staus_Single
0,2,2.0,False,False,True
1,1,0.0,True,False,False
2,2,1.0,False,True,False
3,0,2.0,False,False,True

**VIF helps check if features are too similar to each other, while RFE helps pick the most important features for your model.**